include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y += s5k4h8mipi_Sensor.o
obj-y += s5k4h8_otp.o

subdir-ccflags-y += -Wno-error=unused-variable -Wno-error=return-type -Wno-error=unused-function


