include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += hi842_mipi_raw_Sensor.o  
obj-y += hi842_otp.o

subdir-ccflags-y += -Wno-error=unused-variable -Wno-error=return-type -Wno-error=unused-function

