include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y	:=  af9133.o
